<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PropCore.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />

    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />

    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />

    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PropCore.Application\PropCore.Application.csproj" />
    <ProjectReference Include="..\PropCore.Domain\PropCore.Domain.csproj" />
  </ItemGroup>

</Project>